"""Turning a result into a report a person can actually read.

Three rules the renderer enforces rather than hopes for:

* **Every document carries its own limits.** A section that lists findings
  without saying what they do not prove is how a capability map turns into an
  accusation. :data:`LIMITS_MARKER` must appear in every rendered document, and
  :func:`write` raises if it does not.
* **Prose is generated from numbers.** No document contains a verdict that is
  not derivable from the data in ``results.json``.
* **Evidence ships next to the prose.** Every claim in the reports has a file
  under ``evidence/`` a reader can grep themselves.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from apk_lens.errors import ApkLensError
from apk_lens.report import markdown as md
from apk_lens.results import AnalysisResult
from apk_lens.scan import network as network_scan
from apk_lens.scan import permissions as permissions_scan

LIMITS_MARKER = "### What this section does not prove"
DEFAULT_OUT_DIR = Path("reports")


@dataclass
class ReportSet:
    root: Path
    documents: list[Path] = field(default_factory=list)
    evidence: list[Path] = field(default_factory=list)
    results_json: Path | None = None

    @property
    def readme(self) -> Path:
        return self.root / "README.md"


def _limits(lines: list[str]) -> str:
    return f"{LIMITS_MARKER}\n\n{md.bullets(lines)}"


# --------------------------------------------------------------------- docs


def _readme(result: AnalysisResult) -> str:
    permissions = result.permissions
    counts = permissions.get("counts", {})
    network = result.network
    sinks = result.sinks.get("counts", {})
    sdk_findings = result.sdks.get("findings", [])

    hard = counts.get(permissions_scan.HARD_TO_JUSTIFY, 0)
    notable = counts.get(permissions_scan.NOTABLE, 0)
    unattributed = (network.get("counts") or {}).get(network_scan.UNATTRIBUTED, 0)

    third_party = (network.get("counts") or {}).get(network_scan.THIRD_PARTY, 0)
    first_party = (network.get("counts") or {}).get(network_scan.FIRST_PARTY, 0)
    present = sinks.get("sinks_present", 0)
    catalogued = present + sinks.get("sinks_absent", 0)

    built_to = [
        f"reach {md.plural(third_party, 'domain')} belonging to vendors the catalog "
        f"recognises, and {first_party} of its own",
        f"use {present} of the {catalogued} sensitive Android APIs this tool looks for",
        "ship code from "
        + md.plural(
            len(sdk_findings), "identifiable third party", "identifiable third parties"
        ),
    ]

    body = md.section(
        f"{result.package} {result.version_name}",
        "A static privacy and data-flow report, generated by "
        f"[apk-lens](https://github.com/jacksonmafra-umain/apk-lens) "
        f"{result.tool_version} at analysis depth `{result.depth}`.\n\n"
        + (
            f"Judged as a **{result.category}** app. The same permission is reasonable "
            "in one kind of app and hard to justify in another, so that assumption "
            "shapes the permission verdicts below — change it with `--category`.\n"
            if result.category != permissions_scan.UNKNOWN_CATEGORY
            else "No app category was given, so every sensitive permission is judged "
            "against no expectations at all. Re-run with `--category` (for example "
            "`--category social`) for verdicts that mean something.\n"
        ),
        level=1,
    )

    body += md.section("What the app is built to do", md.bullets(built_to))

    body += md.section(
        "What stands out",
        md.bullets(
            [
                f"{md.plural(hard, 'permission')} hard to justify for this kind of app, "
                f"and {notable} more notable",
                f"{md.plural(unattributed, 'endpoint domain')} could not be attributed to "
                "any known operator — the highest-value thing for a human to review",
                result.native.get("opacity_statement", "No native code was examined."),
            ]
        ),
    )

    absent = permissions.get("notable_absences", {}).get("absent", [])
    body += md.section(
        "What it does not ask for",
        "Absence is evidence too, and a report that only lists requests reads like an "
        "indictment whether or not one is warranted. This app does **not** request:\n\n"
        + md.bullets(name.rsplit(".", 1)[-1] for name in absent[:12]),
    )

    body += md.section(
        "Read the detail",
        md.table(
            ("report", "what is inside"),
            [
                ("[00 · Index and method](00-index.md)", "how this was produced"),
                ("[01 · App overview](01-app-overview.md)", "identity, splits, artefacts"),
                ("[02 · Permissions](02-permissions.md)", "every permission, in context"),
                (
                    "[03 · Manifest and components](03-manifest-components.md)",
                    "what other apps can reach",
                ),
                ("[04 · Endpoints](04-network-endpoints.md)", "every host, grouped and named"),
                ("[05 · Data collection](05-data-collection.md)", "sensitive APIs with call sites"),
                ("[06 · Third parties](06-third-party-sdks.md)", "whose SDKs are bundled"),
                ("[07 · Native and opacity](07-native-and-opacity.md)", "what could not be read"),
                ("[08 · Assessment](08-assessment.md)", "what the evidence supports"),
                ("[09 · Coverage and limits](09-coverage-and-limits.md)", "the honest gaps"),
            ],
        ),
    )

    body += _limits(result.limits())
    return body


def _index(result: AnalysisResult) -> str:
    provenance = result.provenance
    corpus = result.corpus
    body = md.section("00 · Index and method", "", level=1)
    body += md.section(
        "What was analysed",
        md.table(
            ("field", "value"),
            [
                ("package", result.package),
                ("version", f"{result.version_name} (code {result.manifest.get('version_code')})"),
                ("file", provenance.get("filename")),
                ("size", f"{(provenance.get('size_bytes') or 0) / 1024 / 1024:.1f} MB"),
                ("sha256", provenance.get("sha256")),
                ("source", provenance.get("source")),
                ("container", provenance.get("container")),
                ("acquired", provenance.get("acquired_at")),
            ],
        )
        + "\nThe binary itself is **not** part of this report. The SHA-256 above "
        "identifies exactly which bytes were read, so the run can be repeated.\n",
    )

    body += md.section(
        "Method",
        md.numbered(
            [
                "The bundle was unpacked and its split APKs classified.",
                "The binary manifest was decoded — no decompiler needed.",
                "Printable strings were extracted from every dex file and native library.",
                (
                    f"The app was decompiled with jadx ({corpus.get('java_files', 0):,} "
                    "Java files produced)."
                    if result.has_source
                    else "No decompilation was performed (depth: strings)."
                ),
                "Catalog rules were matched against the whole corpus, not a sample.",
                "Findings were grouped, attributed, and cross-referenced against each other.",
            ]
        )
        + "\nNothing was executed. No traffic was captured. No device was involved.\n",
    )

    body += md.section("Evidence", "Raw output backing every claim is in `evidence/`.\n")
    body += _limits(result.limits())
    return body


def _overview(result: AnalysisResult) -> str:
    workspace = result.workspace
    members = workspace.get("members", [])
    corpus = result.corpus

    body = md.section("01 · App overview", "", level=1)
    body += md.section(
        "Identity",
        md.table(
            ("field", "value"),
            [
                ("package", result.package),
                ("version name", result.version_name),
                ("version code", result.manifest.get("version_code")),
                ("min SDK", result.manifest.get("min_sdk")),
                ("target SDK", result.manifest.get("target_sdk")),
                ("declared app class", result.manifest.get("app_name") or "default"),
            ],
        ),
    )

    body += md.section(
        "Bundle structure",
        md.table(
            ("split", "role", "holds", "size", "entries"),
            [
                (
                    member.get("name"),
                    member.get("role"),
                    member.get("abi") or "",
                    f"{(member.get('size_bytes') or 0) / 1024 / 1024:.1f} MB",
                    member.get("entry_count"),
                )
                for member in members
            ],
        )
        + "\nAn app is not one APK. Code lives in the base split; native libraries live "
        "in per-architecture splits, so an analysis that opens only the base APK sees no "
        "native code at all.\n",
    )

    signing = workspace.get("signing") or {}
    if signing.get("signers"):
        body += md.section(
            "Signing certificate",
            md.table(
                ("signer", "sha256"),
                [(entry.get("index"), entry.get("sha256")) for entry in signing["signers"]],
            )
            + f"\n{signing.get('compare_with', '')}\n",
        )

    body += md.section(
        "Artefacts read",
        md.table(
            ("artefact", "count"),
            [
                ("dex files", len(workspace.get("dex_files", []))),
                ("native libraries", len(workspace.get("native_libs", []))),
                ("assets extracted", len(workspace.get("asset_files", []))),
                ("dex strings", f"{corpus.get('dex_string_count', 0):,}"),
                ("native strings", f"{corpus.get('native_string_count', 0):,}"),
                ("decompiled java files", f"{corpus.get('java_files', 0):,}"),
            ],
        ),
    )

    body += _limits(
        [
            "File counts measure how much text was read, not how much of the app's "
            "behaviour is understood.",
            *result.limits()[:1],
        ]
    )
    return body


def _permissions(result: AnalysisResult) -> str:
    report = result.permissions
    findings = report.get("findings", [])

    body = md.section("02 · Permissions", "", level=1)
    body += md.section(
        "How to read this",
        (
            f"Every permission below is judged for a **{result.category}** app. A "
            "permission expected in one kind of app can be hard to justify in another, "
            "which is why the same list produces different verdicts under a different "
            "`--category`.\n"
            if result.category != permissions_scan.UNKNOWN_CATEGORY
            else "No app category was given for this run, so nothing here is compared "
            "against what such an app would normally need. Re-run with `--category` to "
            "get verdicts worth quoting.\n"
        ),
    )

    for verdict in permissions_scan.VERDICT_ORDER:
        group = [finding for finding in findings if finding.get("verdict") == verdict]
        if not group:
            continue
        body += md.section(
            f"{verdict.capitalize()} ({len(group)})",
            md.table(
                ("permission", "what it allows", "normally for"),
                [
                    (
                        finding["name"].rsplit(".", 1)[-1],
                        finding.get("means"),
                        finding.get("justified_when"),
                    )
                    for finding in group
                ],
            ),
        )

    dual_use = [finding for finding in findings if finding.get("also_used_for")]
    if dual_use:
        body += md.section(
            "Also commonly used for something the user did not ask for",
            md.table(
                ("permission", "the other use"),
                [
                    (finding["name"].rsplit(".", 1)[-1], finding["also_used_for"])
                    for finding in dual_use
                ],
            ),
        )

    absences = report.get("notable_absences", {})
    body += md.section(
        "Dangerous permissions NOT requested",
        md.bullets(name.rsplit(".", 1)[-1] for name in absences.get("absent", []))
        + "\nRequested from that same watchlist: "
        + (
            ", ".join(name.rsplit(".", 1)[-1] for name in absences.get("present", []))
            or "none"
        )
        + "\n",
    )

    body += _limits(
        [
            "A declared permission is a request, not a use. The app may never exercise it.",
            "Android grants dangerous permissions at runtime, so the user may have "
            "refused any of these.",
            "Permission classification depends on the app category assumed for this run "
            f"(`{result.category}`).",
        ]
    )
    return body


def _components(result: AnalysisResult) -> str:
    facts = result.manifest
    components = facts.get("components", [])
    exposed = [component for component in components if component.get("exported")]
    unguarded = [
        component
        for component in exposed
        if not component.get("permission")
    ]

    body = md.section("03 · Manifest and components", "", level=1)
    body += md.section(
        "Reachable from other apps",
        md.table(
            ("kind", "name", "guarded by", "why exported"),
            [
                (
                    component.get("kind"),
                    component.get("name"),
                    component.get("permission") or "nothing",
                    component.get("exported_source"),
                )
                for component in exposed
            ],
        )
        + f"\n{len(unguarded)} of {len(exposed)} exported components have no permission "
        "guard, which means any other app on the device can send them an intent. Whether "
        "that matters depends on what they do with it — the manifest cannot say.\n",
    )

    queried = facts.get("queried_packages", [])
    body += md.section(
        f"Other apps this app checks for ({len(queried)})",
        (
            "`<queries>` declares which packages the app is allowed to look up. This is "
            "how an app detects wallets, messengers, or competitors.\n\n"
            + md.bullets(queried[:60])
        )
        if queried
        else "The app declares no `<queries>` entries.\n",
    )

    body += md.section(
        "Network and backup posture",
        md.table(
            ("setting", "value", "what it means"),
            [
                (
                    "usesCleartextTraffic",
                    facts.get("uses_cleartext_traffic"),
                    "whether unencrypted HTTP is permitted",
                ),
                (
                    "networkSecurityConfig",
                    facts.get("network_security_config") or "none",
                    "a policy file can pin certificates or allow exceptions",
                ),
                (
                    "allowBackup",
                    facts.get("allow_backup"),
                    "whether app data can be extracted through platform backup",
                ),
                (
                    "debuggable",
                    facts.get("debuggable"),
                    "a shipped debuggable build would be a serious finding",
                ),
            ],
        ),
    )

    body += _limits(
        [
            "An exported component is reachable; whether it is exploitable depends on "
            "code this section does not read.",
            "`android:exported` is often undeclared, and the effective value then depends "
            "on the target SDK — each row states how it was decided.",
        ]
    )
    return body


def _network(result: AnalysisResult) -> str:
    census = result.network
    findings = census.get("findings", [])

    body = md.section("04 · Network endpoints", "", level=1)
    body += md.section(
        "Scale",
        md.table(
            ("measure", "value"),
            [
                ("URLs found", f"{census.get('url_count', 0):,}"),
                ("distinct hostnames", f"{census.get('host_count', 0):,}"),
                ("registrable domains", f"{len(findings):,}"),
                *[(f"— {key}", value) for key, value in (census.get("counts") or {}).items()],
            ],
        ),
    )

    purposes = census.get("purposes") or {}
    if purposes:
        body += md.section(
            "What those domains are for",
            md.table(("purpose", "domains"), sorted(purposes.items(), key=lambda kv: -kv[1])),
        )

    for bucket in network_scan.BUCKET_ORDER:
        group = [finding for finding in findings if finding.get("bucket") == bucket]
        if not group:
            continue
        meaning = (census.get("bucket_meaning") or {}).get(bucket, "")
        body += md.section(
            f"{bucket.capitalize()} ({len(group)})",
            (md.quote(meaning) + "\n" if meaning else "")
            + md.table(
                ("domain", "hosts", "operator", "purpose", "cleartext"),
                [
                    (
                        finding.get("domain"),
                        len(finding.get("hosts", [])),
                        finding.get("operator") or "—",
                        finding.get("purpose") or "—",
                        "yes" if finding.get("cleartext") else "",
                    )
                    for finding in group[:80]
                ],
            ),
        )

    body += _limits(
        [
            "A host in the code is a host the app is built to reach. It is not proof a "
            "request was made, nor how often.",
            "Attribution comes from a bundled catalog. An unattributed domain is unknown "
            "to the catalog, which is not the same as suspicious.",
            *[
                note
                for note in census.get("notes", [])
                if "public_suffixes.txt" in note or "http://" in note
            ],
        ]
    )
    return body


def _data_collection(result: AnalysisResult) -> str:
    report = result.sinks
    present = report.get("present", [])
    absent = report.get("absent", [])

    body = md.section("05 · Data collection", "", level=1)
    body += md.section(
        "How to read this",
        "Each row is an Android API the app's code references. The `origin` column "
        "separates the app's own code from bundled third-party code, because a sensitive "
        "call inside a vendor library is not the app itself making it.\n",
    )

    grouped: dict[str, list[dict]] = {}
    for finding in present:
        grouped.setdefault(finding.get("category_label", "other"), []).append(finding)

    for label, group in grouped.items():
        body += md.section(
            label,
            md.table(
                ("api", "matches", "origin", "what it allows", "sample citation"),
                [
                    (
                        finding.get("sink_id"),
                        finding.get("total_hits"),
                        ", ".join(
                            f"{origin}: {count}"
                            for origin, count in sorted(
                                (finding.get("origin_counts") or {}).items()
                            )
                        )
                        or "—",
                        finding.get("means"),
                        (finding.get("citations") or ["—"])[0],
                    )
                    for finding in group
                ],
            ),
        )

    body += md.section(
        "What would be needed to prove any of this",
        md.table(
            ("api", "what would settle it"),
            [(finding.get("sink_id"), finding.get("proven_by")) for finding in present],
        ),
    )

    body += md.section(
        f"Catalogued APIs NOT found ({len(absent)})",
        md.table(
            ("api", "category", "would have allowed"),
            [
                (finding.get("sink_id"), finding.get("category"), finding.get("means"))
                for finding in absent
            ],
        ),
    )

    body += _limits(
        [
            "A call site proves a capability is wired up. It does not prove the call runs, "
            "when it runs, or what it sends.",
            "Origin attribution uses package paths and is a heuristic.",
            *[note for note in report.get("notes", []) if "depth strings" in note],
        ]
    )
    return body


def _third_parties(result: AnalysisResult) -> str:
    report = result.sdks
    findings = report.get("findings", [])

    body = md.section("06 · Third-party SDKs", "", level=1)
    body += md.section(
        "Detected",
        md.table(
            ("vendor", "category", "confidence", "evidence", "endpoints seen"),
            [
                (
                    finding.get("vendor"),
                    finding.get("category"),
                    finding.get("confidence"),
                    "; ".join(finding.get("evidence", [])),
                    ", ".join(finding.get("hosts_seen", [])) or "—",
                )
                for finding in findings
            ],
        ),
    )

    body += md.section(
        "What each vendor documents that it handles",
        "Each line paraphrases the vendor's own documentation about its product. It is "
        "not a measurement of this app.\n\n"
        + md.table(
            ("vendor", "documented collection", "policy"),
            [
                (finding.get("vendor"), finding.get("collects"), finding.get("docs"))
                for finding in findings
                if finding.get("collects")
            ],
        ),
    )

    mismatched = [
        finding
        for finding in findings
        if finding.get("hosts_declared") and not finding.get("hosts_seen")
    ]
    if mismatched:
        body += md.section(
            "Bundled, but no matching endpoint found",
            md.table(
                ("vendor", "what that could mean"),
                [(finding.get("vendor"), finding.get("traffic_status")) for finding in mismatched],
            ),
        )

    orphans = report.get("vendor_domains_without_code", [])
    if orphans:
        body += md.section(
            "Vendor domains with no vendor code",
            md.bullets(orphans)
            + "\nUsually a server-side integration, a stale string, or an SDK whose "
            "package was renamed.\n",
        )

    body += _limits(
        [
            "A bundled SDK is code the app ships. It is not proof the app initialises it, "
            "or sends it anything.",
            "Detection backed only by a hostname is reported as `possible`, because a "
            "string can be stale or inherited from a dependency.",
        ]
    )
    return body


def _native(result: AnalysisResult) -> str:
    report = result.native
    libraries = report.get("libraries", [])

    body = md.section("07 · Native code and opacity", "", level=1)
    body += md.section(
        "The size of the blind spot",
        md.quote(report.get("opacity_statement", "No native code was examined.")),
    )

    if libraries:
        body += md.section(
            "Libraries",
            md.table(
                ("library", "abi", "size", "identified as", "markers"),
                [
                    (
                        lib.get("name"),
                        lib.get("abi"),
                        f"{(lib.get('size_bytes') or 0) / 1024 / 1024:.1f} MB",
                        lib.get("identified_as") or "unrecognised",
                        ", ".join(sorted({m["name"] for m in lib.get("markers", [])})),
                    )
                    for lib in libraries
                ],
            ),
        )

        meanings = {
            marker["name"]: marker["meaning"]
            for lib in libraries
            for marker in lib.get("markers", [])
        }
        if meanings:
            body += md.section(
                "What those markers mean",
                md.table(("marker", "meaning"), sorted(meanings.items()))
                + "\nThese describe what a library contains, not why. A fingerprinting "
                "or anti-debugging library is a fact about the app; its purpose is a "
                "question this method cannot answer.\n",
            )

        with_hosts = [lib for lib in libraries if lib.get("hosts")]
        if with_hosts:
            body += md.section(
                "Hosts embedded in native code",
                md.table(
                    ("library", "hosts"),
                    [(lib["name"], ", ".join(lib["hosts"])) for lib in with_hosts],
                )
                + "\nA Java-only analysis would never see these.\n",
            )

    decoded = report.get("decoded_assets", [])
    if decoded:
        body += md.section(
            "Assets that decoded to readable configuration",
            md.table(
                ("asset", "transform", "key", "preview"),
                [
                    (
                        Path(item["source"]).name,
                        item["transform"],
                        item.get("key") or "—",
                        item["preview"][:120],
                    )
                    for item in decoded
                ],
            )
            + "\nReproduction commands are in `evidence/decoded-assets.md`.\n",
        )

    body += _limits(
        [
            "Native libraries were read as text. Nothing was disassembled and nothing was "
            "executed, so their logic is unverified.",
            "A marker's presence describes contents, not intent.",
        ]
    )
    return body


def _assessment(result: AnalysisResult) -> str:
    permissions = result.permissions.get("counts", {})
    network_counts = result.network.get("counts", {})
    sink_counts = result.sinks.get("counts", {})
    sdk_findings = result.sdks.get("findings", [])

    supported = [
        "The app declares "
        + md.plural(len(result.manifest.get("permissions", [])), "permission")
        + "; "
        f"{permissions.get(permissions_scan.HARD_TO_JUSTIFY, 0)} are hard to justify for "
        f"a {result.category} app and {permissions.get(permissions_scan.NOTABLE, 0)} are "
        "notable.",
        f"It is built to reach {len(result.network.get('findings', []))} registrable "
        f"domains, of which {network_counts.get(network_scan.UNATTRIBUTED, 0)} are "
        "unattributed and "
        f"{network_counts.get(network_scan.THIRD_PARTY, 0)} belong to recognised vendors.",
        f"It references {sink_counts.get('sinks_present', 0)} sensitive Android APIs and "
        f"none of the other {sink_counts.get('sinks_absent', 0)} in the catalog.",
        "It ships code from "
        + md.plural(
            len(sdk_findings), "identifiable third party", "identifiable third parties"
        )
        + ".",
    ]

    unsupported = [
        "Whether any of these capabilities is exercised, ever.",
        "What any request actually contains.",
        "Whether the user granted the runtime permissions at all.",
        "What the native libraries do.",
        "What server-pushed configuration changes after install.",
    ]

    next_steps = [
        "Install the app on a device or emulator you control.",
        "Put a TLS-intercepting proxy in front of it, and unpin certificates if needed.",
        "Hook the specific APIs listed in report 05 to see when they fire and with what.",
        "Compare what leaves the device against the endpoint list in report 04.",
        "Disassemble the native libraries named in report 07 if telemetry is assembled there.",
    ]

    body = md.section("08 · Assessment", "", level=1)
    body += md.section(
        "What this evidence supports",
        md.bullets(supported)
        + "\nThese are counts of capabilities present in the package. They describe how "
        "the app was built, which is a different claim from how it behaves.\n",
    )
    body += md.section("What this evidence cannot support", md.bullets(unsupported))
    body += md.section(
        "How to close the gap",
        md.numbered(next_steps)
        + "\nThat is dynamic analysis, and it is the only way to turn any capability "
        "above into an observed behaviour.\n",
    )
    body += _limits(
        [
            "This section is generated from counts, not from judgement. It deliberately "
            "contains no verdict about the app or its developers.",
            "A high count is not misconduct, and a low count is not safety.",
        ]
    )
    return body


def _coverage(result: AnalysisResult) -> str:
    corpus = result.corpus
    body = md.section("09 · Coverage and limits", "", level=1)
    body += md.section("Everything this report cannot tell you", md.bullets(result.limits()))
    body += md.section(
        "What was actually read",
        md.table(
            ("input", "amount"),
            [
                ("dex files", len(result.workspace.get("dex_files", []))),
                ("native libraries", len(result.workspace.get("native_libs", []))),
                ("assets", len(result.workspace.get("asset_files", []))),
                ("decompiled java files", f"{corpus.get('java_files', 0):,}"),
                ("dex strings", f"{corpus.get('dex_string_count', 0):,}"),
                ("native strings", f"{corpus.get('native_string_count', 0):,}"),
                ("analysis depth", result.depth),
                ("evidence strength", corpus.get("evidence_strength")),
            ],
        ),
    )
    notes = [
        *corpus.get("notes", []),
        *result.network.get("notes", []),
        *result.sinks.get("notes", []),
        *result.sdks.get("notes", []),
        *result.native.get("notes", []),
    ]
    body += md.section("Notes recorded by each stage", md.bullets(dict.fromkeys(notes)))
    body += _limits(
        [
            "This page is the honest version of the whole report: read it before quoting "
            "anything from the others.",
        ]
    )
    return body


DOCUMENTS = (
    ("README.md", _readme),
    ("00-index.md", _index),
    ("01-app-overview.md", _overview),
    ("02-permissions.md", _permissions),
    ("03-manifest-components.md", _components),
    ("04-network-endpoints.md", _network),
    ("05-data-collection.md", _data_collection),
    ("06-third-party-sdks.md", _third_parties),
    ("07-native-and-opacity.md", _native),
    ("08-assessment.md", _assessment),
    ("09-coverage-and-limits.md", _coverage),
)


# ----------------------------------------------------------------- evidence


def _write_evidence(result: AnalysisResult, root: Path) -> list[Path]:
    directory = root / "evidence"
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    def write(name: str, text: str) -> None:
        path = directory / name
        path.write_text(text)
        written.append(path)

    findings = result.network.get("findings", [])
    hosts = sorted({host for finding in findings for host in finding.get("hosts", [])})
    write("hosts.txt", "\n".join(hosts) + "\n" if hosts else "")

    write(
        "domains.csv",
        "domain,bucket,host_count,operator,purpose\n"
        + "".join(
            f"{finding.get('domain')},{finding.get('bucket')},"
            f"{len(finding.get('hosts', []))},"
            f"\"{finding.get('operator') or ''}\",{finding.get('purpose') or ''}\n"
            for finding in findings
        ),
    )

    sample_urls = sorted({url for finding in findings for url in finding.get("sample_urls", [])})
    write("urls-sample.txt", "\n".join(sample_urls) + "\n" if sample_urls else "")

    cleartext = result.network.get("cleartext_urls", [])
    write("cleartext-urls.txt", "\n".join(cleartext) + "\n" if cleartext else "")

    write(
        "permissions.csv",
        "permission,verdict,tier\n"
        + "".join(
            f"{finding['name']},{finding['verdict']},{finding['tier']}\n"
            for finding in result.permissions.get("findings", [])
        ),
    )

    write(
        "sinks.tsv",
        "api\tcategory\tmatches\torigins\tcitations\n"
        + "".join(
            "\t".join(
                [
                    finding.get("sink_id", ""),
                    finding.get("category_label", ""),
                    str(finding.get("total_hits", 0)),
                    ";".join(f"{k}={v}" for k, v in (finding.get("origin_counts") or {}).items()),
                    ";".join(finding.get("citations", [])),
                ]
            )
            + "\n"
            for finding in result.sinks.get("present", [])
        ),
    )

    write(
        "native-libraries.csv",
        "library,abi,size_bytes,identified_as,markers\n"
        + "".join(
            f"{lib.get('name')},{lib.get('abi')},{lib.get('size_bytes')},"
            f"\"{lib.get('identified_as') or ''}\","
            f"\"{';'.join(sorted({m['name'] for m in lib.get('markers', [])}))}\"\n"
            for lib in result.native.get("libraries", [])
        ),
    )

    decoded = result.native.get("decoded_assets", [])
    if decoded:
        blocks = [
            f"## {Path(item['source']).name}\n\n"
            f"- transform: `{item['transform']}`\n"
            f"- key: `{item.get('key') or 'n/a'}`\n"
            f"- reproduce:\n\n```sh\n{item['reproduce']}\n```\n\n"
            f"```\n{item['preview']}\n```\n"
            for item in decoded
        ]
        write("decoded-assets.md", "# Decoded assets\n\n" + "\n".join(blocks))

    return written


# -------------------------------------------------------------------- write


def write(result: AnalysisResult, out_dir: Path | None = None) -> ReportSet:
    """Render the full report set for ``result`` and return what was written."""
    root = (out_dir or DEFAULT_OUT_DIR) / result.slug
    root.mkdir(parents=True, exist_ok=True)
    produced = ReportSet(root=root)

    for name, builder in DOCUMENTS:
        content = builder(result)
        if LIMITS_MARKER not in content:
            raise ApkLensError(
                f"report {name} was rendered without its limits section",
                hint=(
                    "every document must state what it does not prove; add a "
                    f"'{LIMITS_MARKER}' block to its builder"
                ),
            )
        path = root / name
        path.write_text(content)
        produced.documents.append(path)

    produced.evidence = _write_evidence(result, root)

    results_path = root / "results.json"
    results_path.write_text(json.dumps(result.to_dict(), indent=2) + "\n")
    produced.results_json = results_path

    return produced
